name: Lint

on:
  push: { branches: ["0.x"] }
  pull_request: { branches: ["0.x"] }

jobs:
  luacheck:
    name: Luacheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install luarocks
        run: sudo apt update && sudo apt install -y luarocks

      - name: Install luacheck
        run: sudo luarocks install luacheck

      - name: Run luacheck
        run: luacheck .

  stylua:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run stylua
        uses: JohnnyMorganz/stylua-action@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
