name: Test

on:
  push: { branches: ["0.x"] }
  pull_request: { branches: ["0.x"] }

jobs:
  test:
    name: Test
    strategy:
      matrix:
        download: ["v0.9.5/nvim-linux64.tar.gz", "stable/nvim-linux-x86_64.tar.gz", "nightly/nvim-linux-x86_64.tar.gz"]
        sapling:
          - name: latest
            latest: "true"
            tag: ""
          - name: "0.2.20260317-201835+0234c21f"
            latest: "false"
            tag: "0.2.20260317-201835+0234c21f"
    runs-on: ubuntu-22.04
    steps:
      - name: Download sapling
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "facebook/sapling"
          latest: ${{ matrix.sapling.latest }}
          tag: ${{ matrix.sapling.tag }}
          fileName: "*linux-x64.tar.xz"

      - name: Install sapling
        run: |
          mkdir -p "${RUNNER_TEMP}/sapling"
          tar -xJf ./*.tar.xz -C "${RUNNER_TEMP}/sapling"
          echo "${RUNNER_TEMP}/sapling" >> "${GITHUB_PATH}"

      - name: Clean up the sapling archive
        run: rm ./*.tar.xz

      - name: Clone the repo
        run: |
          sl clone --git "https://github.com/${{ github.repository }}.git" ${{ github.workspace }}

          head_node="$(sl log -r '.' -T"{node}")"
          sl goto "${{ github.sha }}"
          sl rebase -d "${head_node}"

      - name: Install luarocks
        run: sudo apt update && sudo apt install -y luarocks

      - name: Install busted
        run: sudo luarocks install busted

      - name: Install neovim
        run: |
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL "https://github.com/neovim/neovim/releases/download/${{ matrix.download }}" | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }

      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"

          nvim --version
          nvim -l ./lua/sapling_scm_tests/init.lua
