name: Test

on:
  push: { branches: ["0.x"] }
  pull_request: { branches: ["0.x"] }

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Download sapling
        uses: robinraju/release-downloader@v1.9
        with:
          repository: "facebook/sapling"
          latest: true
          fileName: "*amd64.Ubuntu22.04.deb"

      - name: Install sapling
        run: sudo dpkg --install *.deb

      - name: Clone the repo
        run: |
          ls -al .
          ls -al ${{ github.workspace }}
          sl clone --git "https://github.com/${{ github.repository }}.git" ${{ github.workspace }}

          head_node="$(sl log -r '.' -T"{node}")"

          sl goto "${{ github.sha }}"
          sl rebase -d "${head_node}"

      - name: Install luarocks
        run: sudo apt update && sudo apt install -y luarocks

      - name: Install busted
        run: sudo luarocks install busted

      - name: Install neovim
        run: |
          test -d _neovim || {
            mkdir -p _neovim
            curl -sL "https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz" | tar xzf - --strip-components=1 -C "${PWD}/_neovim"
          }

      - name: Run tests
        run: |
          export PATH="${PWD}/_neovim/bin:${PATH}"
          export VIM="${PWD}/_neovim/share/nvim/runtime"

          sl config --local ui.logtemplate ' {graphnode} {node|short} {truncatelonglines(desc|firstline, 80)} ({date|age}) <{author|person}> {if(github_pull_request_number, "PR #{github_pull_request_number}")}\n'

          nvim --version
          nvim -l ../lua/sapling_scm_tests/init.lua
